### ISSUE TITLE
Fix HttpClient 

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/dotnet-mono#25]
Because of some dotnet tooling issues as explained in https://github.com/dotnet/corefx/issues/19914, Httpclient from netstandard2.0 does not work in mono, provide a flag to fix this issue after running `dotnet build`. 

This should delete the System.Net.Http.dll from the bin directory and apply the correct binding redirect to the GAC'd version.

**Comment by robintschroeder** [comment]
Adding the following to the proj file allows the console app to run, but then throws a System.TypeLoadException 
Count not load type of field "WeatherWear.ClassLib.WeatherIndergroundCaller + <CalGeoLookUp>
due to: could not resolve type with token
from typeref, class/assembly, System.Net.Http.HttpClient, netstandard, Version=2.0.0.0 ...

```
<Target Name="AfterBuild">  
   <Delete Files="bin/$(Configuration)/System.Net.Http.dll" /> 
</Target>
```

**Comment by TheAngryByrd** [comment]
What flags did you pass to dotnet mono?

**Comment by TheAngryByrd** [comment]
Closing due to no response. Feel free to keep adding to this though.
